#!/usr/bin/env python3
"""Build the Reader's Remixicon CSS and WOFF2 subset from classes used in src/."""

from pathlib import Path
import re
import sys

try:
    from fontTools import subset
    from fontTools.ttLib import TTFont
except ImportError as exc:
    raise SystemExit("Install the generator dependency first: python -m pip install fonttools brotli") from exc


ROOT = Path(__file__).resolve().parents[1]
SOURCE_ROOT = ROOT / "src"
REMIX_ROOT = ROOT / "node_modules" / "remixicon" / "fonts"
OUTPUT_ROOT = SOURCE_ROOT / "assets" / "icons"
SOURCE_CSS = REMIX_ROOT / "remixicon.css"
SOURCE_FONT = REMIX_ROOT / "remixicon.woff2"


def used_classes():
    names = set()
    for path in SOURCE_ROOT.rglob("*"):
        if path.suffix.lower() not in {".vue", ".js", ".css", ".less"}:
            continue
        names.update(re.findall(r"\bri-[a-z0-9-]+", path.read_text(encoding="utf-8")))
    return sorted(names)


def source_mappings():
    text = SOURCE_CSS.read_text(encoding="utf-8")
    return {
        name: int(codepoint, 16)
        for name, codepoint in re.findall(r"\.(ri-[a-z0-9-]+):before\s*\{\s*content:\s*\"\\([0-9a-f]+)\";\s*\}", text, re.I)
    }


def write_css(names, mappings):
    lines = [
        "/* Generated by scripts/build-icon-subset.py from Remix Icon v2.5.0 (Apache-2.0). */",
        "@font-face {",
        "  font-family: 'po18-remixicon';",
        "  src: url('./po18-icons.woff2') format('woff2');",
        "  font-display: swap;",
        "}",
        "",
        "[class^='ri-'], [class*=' ri-'] {",
        "  font-family: 'po18-remixicon' !important;",
        "  font-style: normal;",
        "  font-weight: normal !important;",
        "  font-variant: normal;",
        "  text-transform: none;",
        "  line-height: 1;",
        "  -webkit-font-smoothing: antialiased;",
        "  -moz-osx-font-smoothing: grayscale;",
        "}",
        ""
    ]
    lines.extend(f'.{name}:before {{ content: "\\{mappings[name]:x}"; }}' for name in names)
    with (OUTPUT_ROOT / "po18-icons.css").open("w", encoding="utf-8", newline="\n") as output:
        output.write("\n".join(lines) + "\n")


def write_font(codepoints):
    options = subset.Options()
    options.flavor = "woff2"
    options.layout_features = ["*"]
    options.name_IDs = [0, 1, 2, 3, 4, 5, 6]
    font = TTFont(SOURCE_FONT)
    worker = subset.Subsetter(options=options)
    worker.populate(unicodes=codepoints)
    worker.subset(font)
    font.save(OUTPUT_ROOT / "po18-icons.woff2")


def main():
    names = used_classes()
    mappings = source_mappings()
    missing = [name for name in names if name not in mappings]
    if missing:
        raise SystemExit(f"Missing Remixicon mappings: {', '.join(missing)}")
    OUTPUT_ROOT.mkdir(parents=True, exist_ok=True)
    write_css(names, mappings)
    write_font([mappings[name] for name in names])
    print(f"Generated {len(names)} icons in {OUTPUT_ROOT}")


if __name__ == "__main__":
    main()
